alter table public.face_reports
  add column if not exists age_bucket text
  check (age_bucket in ('under_35', 'over_35'));

create index if not exists face_reports_age_bucket_idx on public.face_reports (age_bucket);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  report_id uuid references public.face_reports(id) on delete set null,
  message text not null,
  user_agent text,
  ip_hash text
);

create index if not exists feedback_created_at_idx on public.feedback (created_at desc);
create index if not exists feedback_report_id_idx on public.feedback (report_id);

alter table public.feedback enable row level security;

drop policy if exists "anon can insert feedback" on public.feedback;
create policy "anon can insert feedback" on public.feedback
  for insert to anon
  with check (char_length(message) between 1 and 2000);
