create table if not exists public.service_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text,
  report_id uuid references public.face_reports(id) on delete set null,
  event_name text not null,
  phase text,
  level text not null default 'info' check (level in ('debug', 'info', 'warn', 'error')),
  payload jsonb not null default '{}'::jsonb,
  user_agent text,
  ip_hash text
);

create index if not exists service_events_created_at_idx on public.service_events (created_at desc);
create index if not exists service_events_session_id_idx on public.service_events (session_id);
create index if not exists service_events_report_id_idx on public.service_events (report_id);
create index if not exists service_events_event_name_idx on public.service_events (event_name);

alter table public.service_events enable row level security;
